source 'https://rubygems.org'
ruby '2.2.3'

# Dotenv comes first in case a gem needs ENV variables
gem 'dotenv-rails', :require => 'dotenv/rails-now'
gem 'rails', '4.2.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
group :development, :test do
  gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
gem 'bootstrap-sass'
gem 'pg'
gem 'therubyracer', :platform=>:ruby
gem 'unicorn'
gem 'unicorn-rails'
gem 'paperclip'
gem 'aws-sdk', '< 2.0'
group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'foreman'
  gem 'rails_layout'
end
group :development, :test do
  gem 'pry-rails'
  gem 'pry-rescue'
end
group :production do
  gem 'rails_12factor'
end
